; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#include "CodeDependencies.iss"

#define MyAppName "Azookey"
#define MyAppVersion "0.1.0-alpha.1"
#define MyAppPublisher "fkunn1326"
#define MyAppURL "https://github.com/fkunn1326/azooKey-Windows/"
#ifndef BuildProfile
  #define BuildProfile "release"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{80B746D4-D74D-4345-8F81-47E06BCAB515}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
UsePreviousAppDir=no
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=../build
OutputBaseFilename=azookey-setup
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
CloseApplications=no
AlwaysRestart=yes

[Languages]
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Files]
Source: "../build/azookey_windows.dll"; DestDir: "{app}"; DestName: "azookey.dll"; Flags: ignoreversion regserver restartreplace 64bit
Source: "../build/x86/azookey_windows.dll"; DestDir: "{app}"; DestName: "azookey32.dll"; Flags: ignoreversion regserver restartreplace 32bit
Source: "../build/*"; DestDir: "{app}"; Excludes: "azookey-setup.exe"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "../target/{#BuildProfile}/bundle/nsis/Azookey_0.1.0_x64-setup.exe"; Flags: dontcopy noencryption
Source: "./Azookey Startup.xml"; Flags: dontcopy noencryption
Source: "./SetupStartupTask.ps1"; Flags: dontcopy noencryption
Source: "./StopAzookeyRuntime.ps1"; Flags: dontcopy noencryption
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[UninstallDelete]
Type: files; Name: "{app}\launch.vbs"

[Code]
function InitializeSetup: Boolean;
begin
  ExtractTemporaryFile('Azookey_0.1.0_x64-setup.exe');
  Dependency_AddVC2015To2022x64;
  Dependency_AddVC2015To2022x86;
  Dependency_Add('Azookey_0.1.0_x64-setup.exe',
    '/q',
    'Azookey',
    '', '', True, False);

  Result := True;
end;

function UninstallNeedRestart(): Boolean;
begin
  Result := True;
end;

function CmdLineContains(Param: String): Boolean;
var
  I: Integer;
begin
  Result := False;
  for I := 1 to ParamCount do
  begin
    if CompareText(ParamStr(I), Param) = 0 then
    begin
      Result := True;
      Exit;
    end;
  end;
end;
procedure ConfigureStartupTask();
var
  TaskXmlPath: string;
  SetupScriptPath: string;
  Params: string;
  ResultCode: Integer;
  Output: TExecOutput;
  ErrorMessage: string;
  I: Integer;
begin
  ExtractTemporaryFile('Azookey Startup.xml');
  ExtractTemporaryFile('SetupStartupTask.ps1');
  TaskXmlPath := ExpandConstant('{tmp}\Azookey Startup.xml');
  SetupScriptPath := ExpandConstant('{tmp}\SetupStartupTask.ps1');
  Params :=
    '-NoProfile -ExecutionPolicy Bypass -File "' + SetupScriptPath + '"' +
    ' -TaskXmlTemplatePath "' + TaskXmlPath + '"' +
    ' -LaunchVbsPath "' + ExpandConstant('{app}\launch.vbs') + '"' +
    ' -LauncherPath "' + ExpandConstant('{app}\launcher.exe') + '"' +
    ' -TaskName "Azookey Startup"';

  if not ExecAndCaptureOutput(
    ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'),
    Params, '', SW_HIDE,
    ewWaitUntilTerminated, ResultCode, Output) then
  begin
    RaiseException('Failed to start the AzooKey startup-task setup helper.');
  end;
  if ResultCode <> 0 then
  begin
    ErrorMessage := Format(
      'AzooKey startup-task setup failed with exit code %d.', [ResultCode]);
    if Length(Output.StdErr) > 0 then
      for I := 0 to Length(Output.StdErr) - 1 do
        ErrorMessage := ErrorMessage + #13#10 + Output.StdErr[I];
    if Length(Output.StdOut) > 0 then
      for I := 0 to Length(Output.StdOut) - 1 do
        ErrorMessage := ErrorMessage + #13#10 + Output.StdOut[I];
    RaiseException(ErrorMessage);
  end;
end;

procedure StopExistingRuntime();
var
  StopScriptPath: string;
  Params: string;
  ResultCode: Integer;
  Output: TExecOutput;
  ErrorMessage: string;
  I: Integer;
begin
  ExtractTemporaryFile('StopAzookeyRuntime.ps1');
  StopScriptPath := ExpandConstant('{tmp}\StopAzookeyRuntime.ps1');
  Params :=
    '-NoProfile -ExecutionPolicy Bypass -File "' + StopScriptPath + '"' +
    ' -InstallDirectory "' + ExpandConstant('{app}') + '"' +
    ' -TaskName "Azookey Startup"';

  if not ExecAndCaptureOutput(
    ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe'),
    Params, '', SW_HIDE,
    ewWaitUntilTerminated, ResultCode, Output) then
  begin
    RaiseException('Failed to start the AzooKey runtime shutdown helper.');
  end;
  if ResultCode <> 0 then
  begin
    ErrorMessage := Format(
      'AzooKey runtime shutdown failed with exit code %d.', [ResultCode]);
    if Length(Output.StdErr) > 0 then
      for I := 0 to Length(Output.StdErr) - 1 do
        ErrorMessage := ErrorMessage + #13#10 + Output.StdErr[I];
    if Length(Output.StdOut) > 0 then
      for I := 0 to Length(Output.StdOut) - 1 do
        ErrorMessage := ErrorMessage + #13#10 + Output.StdOut[I];
    RaiseException(ErrorMessage);
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  Result := '';
  try
    StopExistingRuntime();
  except
    Result := GetExceptionMessage();
  end;
end;

procedure GrantAppContainerReadExecute(FilePath: string);
var
  Params: string;
  ResultCode: Integer;
begin
  Params := '"' + FilePath + '" /grant "*S-1-15-2-1:(RX)"';
  if not ShellExec('', ExpandConstant('{sys}\icacls.exe'), Params, '', SW_HIDE,
    ewWaitUntilTerminated, ResultCode) then
  begin
    RaiseException('Failed to start icacls for ' + FilePath + '.');
  end;
  if ResultCode <> 0 then
  begin
    RaiseException(Format(
      'icacls failed for %s with exit code %d.', [FilePath, ResultCode]));
  end;
end;

procedure RemoveStartupTask();
var
  QueryResult: Integer;
  DeleteResult: Integer;
begin
  if not ShellExec('', ExpandConstant('{sys}\schtasks.exe'),
    '/Query /TN "Azookey Startup"', '',
    SW_HIDE, ewWaitUntilTerminated, QueryResult) then
  begin
    RaiseException('Failed to query the AzooKey startup task.');
  end;

  { A nonzero query result means that the task is already absent. }
  if QueryResult <> 0 then
    Exit;

  if not ShellExec('', ExpandConstant('{sys}\schtasks.exe'),
    '/Delete /TN "Azookey Startup" /F', '', SW_HIDE,
    ewWaitUntilTerminated, DeleteResult) then
  begin
    RaiseException('Failed to start removal of the AzooKey startup task.');
  end;
  if DeleteResult <> 0 then
  begin
    RaiseException(Format(
      'AzooKey startup-task removal failed with exit code %d.', [DeleteResult]));
  end;
end;


procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    GrantAppContainerReadExecute(ExpandConstant('{app}\azookey.dll'));
    GrantAppContainerReadExecute(ExpandConstant('{app}\azookey32.dll'));
    ConfigureStartupTask();
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = wpFinished then
    WizardForm.RunList.Visible := False;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
  begin
    RemoveStartupTask();
  end;
end;
